### ISSUE TITLE
Investigate webmock dependencies

### ISSUE THREAD

**Issue by jrgriffiniii** [samvera/maintenance#27]
@elrayle successfully restored the build referenced in https://github.com/samvera/questioning_authority/issues/260 by pinning `webmock` to release 3.6.0.  In response to this, the following actions should be taken:
- [ ] Issue a PR to questioning_authority restoring the build
- [ ] Investigate other core components for this potential problem
- [ ] Explore webmock in order to determine if an issue should be made for the Gem

**Comment by jrgriffiniii** [comment]
It should be noted that elrayle did find that `webmock` release 3.6.2 triggered failures on questioning_authority, so this may well be an upstream bug which should be resolved or documented.

**Comment by elrayle** [comment]
Update:  The failures are random, so the pin of webmock did not fix this.

In QA, I tried...
* pinning webmock to 3.6.0 (latest is 3.6.2)
* pinning net-http-persistent to 3.0.1 (latest is 3.1.0)
* forcing the test app cache to regenerate

Rather or not the tests fail for any particular combination of Rails and Ruby versions appears to be random.  Best I can tell, which tests fail are the same each time failures occur.

NOTE: There have been not recent changes to the tests.  And the tests that are failing have been passing consistently for a long time.  Some of the failing tests haven't been touched in 2 years.  This definitely leads me to believe a change in dependencies or infrastructure is the cause of the failures.

**Comment by jrgriffiniii** [comment]
From what I could determine https://circleci.com/gh/samvera/questioning_authority/765 was the first failure, triggered by the merging of https://github.com/samvera/questioning_authority/pull/259 on July 11th.  Nothing within https://github.com/samvera/questioning_authority/pull/259/files updated any dependencies, so I would have to assume that most of the Gems (and their dependencies) in https://github.com/samvera/questioning_authority/blob/master/qa.gemspec might be suspect.

**Comment by jrgriffiniii** [comment]
I'll see about adjusting `faraday` versions as an experiment.
